package cn.ssm.entity;

public class ChannelDown {
	/**
	 * @author 韩超
	 * 添加类型名称
	 */
	private String name;
	
	
    public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_down.id
     *
     * @mbggenerated Wed Sep 13 17:26:20 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_down.channel_name
     *
     * @mbggenerated Wed Sep 13 17:26:20 CST 2017
     */
    private String channelName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_down.type
     *
     * @mbggenerated Wed Sep 13 17:26:20 CST 2017
     */
    private Integer type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_down.id
     *
     * @return the value of channel_down.id
     *
     * @mbggenerated Wed Sep 13 17:26:20 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_down.id
     *
     * @param id the value for channel_down.id
     *
     * @mbggenerated Wed Sep 13 17:26:20 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_down.channel_name
     *
     * @return the value of channel_down.channel_name
     *
     * @mbggenerated Wed Sep 13 17:26:20 CST 2017
     */
    public String getChannelName() {
        return channelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_down.channel_name
     *
     * @param channelName the value for channel_down.channel_name
     *
     * @mbggenerated Wed Sep 13 17:26:20 CST 2017
     */
    public void setChannelName(String channelName) {
        this.channelName = channelName == null ? null : channelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_down.type
     *
     * @return the value of channel_down.type
     *
     * @mbggenerated Wed Sep 13 17:26:20 CST 2017
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_down.type
     *
     * @param type the value for channel_down.type
     *
     * @mbggenerated Wed Sep 13 17:26:20 CST 2017
     */
    public void setType(Integer type) {
        this.type = type;
    }
}