package cn.ssm.mapper.master;


import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import cn.ssm.entity.ChannelDown;
import cn.ssm.entity.ChannelDownExample;
import cn.ssm.entity.channel.ChannelType;

@Mapper
public interface ChannelDownMapper extends BaseMapper<ChannelDown,ChannelDownExample>{

	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_down
     *
     * @mbggenerated Thu Sep 21 13:38:38 CST 2017
     */
    int countByExample(Map<String,Object> params);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_down
     *
     * @mbggenerated Thu Sep 21 13:38:38 CST 2017
     */
    int deleteByExample(ChannelDownExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_down
     *
     * @mbggenerated Thu Sep 21 13:38:38 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_down
     *
     * @mbggenerated Thu Sep 21 13:38:38 CST 2017
     */
    int insert(ChannelDown record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_down
     *
     * @mbggenerated Thu Sep 21 13:38:38 CST 2017
     */
    int insertSelective(ChannelDown record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_down
     *
     * @mbggenerated Thu Sep 21 13:38:38 CST 2017
     */
    List<ChannelDown> selectByExample(ChannelDownExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_down
     *
     * @mbggenerated Thu Sep 21 13:38:38 CST 2017
     */
    ChannelDown selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_down
     *
     * @mbggenerated Thu Sep 21 13:38:38 CST 2017
     */
    int updateByExampleSelective(@Param("record") ChannelDown record, @Param("example") ChannelDownExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_down
     *
     * @mbggenerated Thu Sep 21 13:38:38 CST 2017
     */
    int updateByExample(@Param("record") ChannelDown record, @Param("example") ChannelDownExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_down
     *
     * @mbggenerated Thu Sep 21 13:38:38 CST 2017
     */
    int updateByPrimaryKeySelective(ChannelDown record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_down
     *
     * @mbggenerated Thu Sep 21 13:38:38 CST 2017
     */
    int updateByPrimaryKey(ChannelDown record);

	List<ChannelDown> quryByPage(int param, int pageSize);
	
	/**
	 * 通过渠道名称模糊查询
	 * @param param  查询参数
	 * @return 下游渠道实体列表
	 * @author 张长江
	 */
    List<ChannelDown> selectByChannelName(String param);
    /**
     * 通过渠道类型模糊查询
     * @param string
     * @return 下游渠道实体列表
     * @author 张长江
     */
    List<ChannelType> selectByChannelType(String string);
    /**
	 * @author 韩超
	 * 分页模糊查找所有
	 * @param currPage 当前页
	 * @param pageSize 每页显示条数
	 * @param kw 名称关键字
	 * @param type 类型关键字
	 * @return
	 */
    /**
     * @param params
     */
	List<ChannelDown> quryByConditionPage(Map<String,Object> params);

	/**
	 * 查询所有
	 */
	List<ChannelDown> selectAll();
}