package cn.ssm.entity.channel;

public class ChannelType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_type.id
     *
     * @mbggenerated Thu Sep 21 16:12:56 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_type.typeid
     *
     * @mbggenerated Thu Sep 21 16:12:56 CST 2017
     */
    private String typeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_type.name
     *
     * @mbggenerated Thu Sep 21 16:12:56 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_type.remark
     *
     * @mbggenerated Thu Sep 21 16:12:56 CST 2017
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_type.id
     *
     * @return the value of channel_type.id
     *
     * @mbggenerated Thu Sep 21 16:12:56 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_type.id
     *
     * @param id the value for channel_type.id
     *
     * @mbggenerated Thu Sep 21 16:12:56 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

   

    public String getTypeCode() {
		return typeCode;
	}

	public void setTypeCode(String typeCode) {
		this.typeCode = typeCode;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_type.name
     *
     * @return the value of channel_type.name
     *
     * @mbggenerated Thu Sep 21 16:12:56 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_type.name
     *
     * @param name the value for channel_type.name
     *
     * @mbggenerated Thu Sep 21 16:12:56 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_type.remark
     *
     * @return the value of channel_type.remark
     *
     * @mbggenerated Thu Sep 21 16:12:56 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_type.remark
     *
     * @param remark the value for channel_type.remark
     *
     * @mbggenerated Thu Sep 21 16:12:56 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}